In [1]:
from tensorflow.keras.layers import Dense # Densely connected layer
from tensorflow.keras.models import Sequential # Class that makes intuitive to build models

Building models with the sequential class is super easy, we just create an instance of the sequential class. All we have to pass it are keras layers.

In [2]:
model = Sequential([
    # A densely connected layer, with 64 units and activation function = ReLU
    Dense(64, activation = 'relu'),
    # A densely connected layer with 10 units and activation function = Softmax
    Dense(10, activation = 'softmax')
])

So, our model is a feed forward neural network with 1 hidden layer.  
Notice we're not saying what shape or size the input is going to be, we'll leave that until we pass the data to the model and train it, althought, we can do it as follows.

In [3]:
model = Sequential([
    # A densely connected layer, with 64 units and activation function = ReLU and an input shape of (784, )
    Dense(64, activation = 'relu', input_shape = (784, )),
    # A densely connected layer with 10 units and activation function = Softmax
    Dense(10, activation = 'softmax')
])

**Alternative way of building the exact same model**

In [4]:
# Creata an instance of Sequential without parameters
model = Sequential()

# Using the method .add
model.add(Dense(64, activation = 'relu', input_shape = (784, )))
model.add(Dense(10, activation = 'softmax'))

Another example

In [5]:
from tensorflow.keras.layers import Flatten # Densely connected layer

model = Sequential([
    # Flatten layers, it converts (28, 28) of (784, )
    Flatten(input_shape = (28, 28)),
    Dense(64, activation = 'relu'),
    Dense(10, activation = 'softmax')
])

Creating another model to observe parameters.

In [6]:
model = Sequential([
    Dense(16, activation = 'relu'),
    Dense(16, activation = 'relu'),
    Dense(10, activation = 'softmax')
])

In [7]:
# Model summary
model.weights

ValueError: Weights for model sequential_4 have not yet been created. Weights are created when the Model is first called on inputs or `build()` is called with an `input_shape`.

As we see, we get an error, because weights have not been initialized yet. We can correct this by especifying the input shape with a Flatten layer.

In [8]:
model = Sequential([
    Flatten(input_shape = (28, 28)),
    Dense(16, activation = 'relu'),
    Dense(16, activation = 'relu'),
    Dense(10, activation = 'softmax')
])

In [9]:
# Model summary
model.weights

[<tf.Variable 'dense_11/kernel:0' shape=(784, 16) dtype=float32, numpy=
 array([[-0.07010983,  0.04464896, -0.01042422, ...,  0.08179359,
          0.01586717,  0.08377422],
        [-0.06401981, -0.02058074,  0.03853139, ...,  0.06305715,
         -0.0347984 , -0.0202671 ],
        [-0.05600139, -0.00599781, -0.07913804, ...,  0.06600524,
         -0.07168556,  0.01600332],
        ...,
        [ 0.01986713,  0.07920857,  0.00680142, ..., -0.07577424,
          0.04798478, -0.07602974],
        [ 0.0253374 , -0.02869768,  0.01324409, ..., -0.01742148,
          0.04446584,  0.02060466],
        [-0.06976896, -0.00894585,  0.05719548, ..., -0.05273601,
         -0.05332655, -0.05914855]], dtype=float32)>,
 <tf.Variable 'dense_11/bias:0' shape=(16,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>,
 <tf.Variable 'dense_12/kernel:0' shape=(16, 16) dtype=float32, numpy=
 array([[ 0.27107057,  0.07212761,  0.3166612 ,  0.

As you can see, the output is pretty messy, luckily, there is a better way to visualize the summary of a model.

In [11]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_11 (Dense)             (None, 16)                12560     
_________________________________________________________________
dense_12 (Dense)             (None, 16)                272       
_________________________________________________________________
dense_13 (Dense)             (None, 10)                170       
Total params: 13,002
Trainable params: 13,002
Non-trainable params: 0
_________________________________________________________________
