In [1]:
import tensorflow as tf

Basic units of tensorflow are tensors (dah). Tensors are n-dimensional arrays, the dimension of the array gives the rank of the tensor.
* 0-dimensional array -> rank 0 tensor
* 1-dimensional array -> rank 1 tensor
* 2-dimensional array -> rank 2 tensor
* 3-dimensional array -> rank 3 tensor
and so on.  

Let's create a rank 0 tensor and see the output.

In [4]:
rank0 = tf.constant(3)
print(rank0)

tf.Tensor(3, shape=(), dtype=int32)


We see that the shape is (), refering to a single value. Let' see a rank 1 tensor.

In [5]:
rank1 = tf.constant([1, 2, 3])
print(rank1)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


We now see that the shape is (3,), refering to a 1-dimensional array with 3 elements. Finally, let's take a look at higher rank tensors.

In [12]:
rank2 = tf.constant([[1, 2, 3], [4, 5, 6]])
print('Rank 2 tensor\n' + str(rank2) + '\n')

rank3 = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print('Rank 3 tensor\n' + str(rank3) + '\n')

# A weird array
aux1 = tf.constant([2, 3, 4])
aux2 = tf.stack([aux1, aux1])
aux3 = tf.stack([aux2, aux2, aux2, aux2])
rankn = tf.stack([aux3, aux3, aux3, aux3, aux3])
print('Rank n tensor\n' + str(rankn) + '\n')

Rank 2 tensor
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Rank 3 tensor
tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(1, 3, 3), dtype=int32)

Rank n tensor
tf.Tensor(
[[[[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]]


 [[[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]]


 [[[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]]


 [[[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]]


 [[[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]

  [[2 3 4]
   [2 3 4]]]], shape=(5, 4, 2, 3), dtype=int32)



We've been using tf.constant to define our values but there is also tf.variable. The difference is pretty obvious.
* tf.constant can't be modified
* tf.Variable can be modified  

Let's see some examples on tf.Variable

In [28]:
variable1 = tf.Variable(2.0, dtype = tf.float32, name = 'variable1')
print('Declaring the variable with the value 2.0')
print(str(variable1) + '\n')

variable1.assign(45.8)
print('Assigning the value 45.8 to the variable')
print(str(variable1) + '\n')

variable1.assign_add(4.2)
print('Adding 4.2 to the variable')
print(str(variable1) + '\n')

variable1.assign_sub(40.0)
print('Substracting 40.0 to the variable')
print(str(variable1))

Declaring the variable with the value 2.0
<tf.Variable 'variable1:0' shape=() dtype=float32, numpy=2.0>

Assigning the value 45.8 to the variable
<tf.Variable 'variable1:0' shape=() dtype=float32, numpy=45.8>

Adding 4.2 to the variable
<tf.Variable 'variable1:0' shape=() dtype=float32, numpy=50.0>

Substracting 40.0 to the variable
<tf.Variable 'variable1:0' shape=() dtype=float32, numpy=10.0>


Now, we'll see how to perform operations between Variables and constants

In [32]:
w = tf.Variable([[1.], [2.]])
x = tf.constant([[3., 4.]])
tf.matmul(w, x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>

Tensorflow is a library that can be used for any numeric computation, not just DL. And so, TF has the hability to compute the partial derivative of any function with respect to any variable.
Speaking of DL, in the update step, TF needs to remember which operations were done and in which order.
**Gradient Tape** is a context manager in which those partial derivatives are calculated, and it needs that the operations are expresed in TF in built operations only.  
A way of computing gradients is the next one.

In [35]:
def compute_gradients(X, Y, w0, w1):
    
    # Record the computation with GradientTape (when it is executed, not when it is defined!)
    with tf.GradientTape() as tape:
        loss = loss_mse(X, Y, w0, w1)
    
    # Selecting the loss function you'll use and the variables you want the gradient with
    # respect to ([w0, w1])
    return tape.gradient(loss, [wo, w1])